# Generated by Django 4.0.6 on 2022-10-08 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Country',
            new_name='District',
        ),
        migrations.RenameField(
            model_name='city',
            old_name='country',
            new_name='district',
        ),
        migrations.RenameField(
            model_name='person',
            old_name='country',
            new_name='district',
        ),
    ]
