# Generated by Django 4.0.6 on 2022-10-08 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0003_account_person_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='dob',
            field=models.DateField(blank=True, null=True),
        ),
    ]
