# Generated by Django 4.0.6 on 2022-10-09 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0007_person_creditcard'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='chequebook',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='person',
            name='debitcard',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='person',
            name='creditcard',
            field=models.BooleanField(default=False),
        ),
    ]
