# Generated by Django 4.0.6 on 2022-10-09 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0009_alter_person_dob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='dob',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
